# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sataDataDownload_V3_ui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(446, 440)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabwidget = QtGui.QTabWidget(self.centralwidget)
        self.tabwidget.setGeometry(QtCore.QRect(10, 10, 421, 401))
        self.tabwidget.setObjectName(_fromUtf8("tabwidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.outLabel_l = QtGui.QLabel(self.tab)
        self.outLabel_l.setGeometry(QtCore.QRect(320, 300, 71, 21))
        self.outLabel_l.setObjectName(_fromUtf8("outLabel_l"))
        self.searchBar_l = QtGui.QProgressBar(self.tab)
        self.searchBar_l.setGeometry(QtCore.QRect(110, 300, 201, 23))
        self.searchBar_l.setProperty("value", 24)
        self.searchBar_l.setObjectName(_fromUtf8("searchBar_l"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 100, 391, 80))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.sate_l = QtGui.QComboBox(self.groupBox_4)
        self.sate_l.setGeometry(QtCore.QRect(40, 30, 101, 22))
        self.sate_l.setObjectName(_fromUtf8("sate_l"))
        self.label_8 = QtGui.QLabel(self.groupBox_4)
        self.label_8.setGeometry(QtCore.QRect(10, 35, 54, 12))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.groupBox_4)
        self.label_9.setGeometry(QtCore.QRect(170, 34, 54, 12))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.cloud_l = QtGui.QComboBox(self.groupBox_4)
        self.cloud_l.setGeometry(QtCore.QRect(220, 30, 101, 22))
        self.cloud_l.setObjectName(_fromUtf8("cloud_l"))
        self.label_10 = QtGui.QLabel(self.groupBox_4)
        self.label_10.setGeometry(QtCore.QRect(200, 30, 16, 21))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 190, 391, 101))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.label_11 = QtGui.QLabel(self.groupBox_5)
        self.label_11.setGeometry(QtCore.QRect(10, 30, 54, 12))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.groupBox_5)
        self.label_12.setGeometry(QtCore.QRect(10, 63, 54, 12))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.savecsv_l = QtGui.QLineEdit(self.groupBox_5)
        self.savecsv_l.setGeometry(QtCore.QRect(60, 28, 241, 20))
        self.savecsv_l.setObjectName(_fromUtf8("savecsv_l"))
        self.savedownload_l = QtGui.QLineEdit(self.groupBox_5)
        self.savedownload_l.setGeometry(QtCore.QRect(60, 60, 241, 20))
        self.savedownload_l.setObjectName(_fromUtf8("savedownload_l"))
        self.slt_csv_bttn_l = QtGui.QPushButton(self.groupBox_5)
        self.slt_csv_bttn_l.setGeometry(QtCore.QRect(310, 27, 75, 23))
        self.slt_csv_bttn_l.setObjectName(_fromUtf8("slt_csv_bttn_l"))
        self.slt_downpath_bttn_l = QtGui.QPushButton(self.groupBox_5)
        self.slt_downpath_bttn_l.setGeometry(QtCore.QRect(310, 60, 75, 23))
        self.slt_downpath_bttn_l.setObjectName(_fromUtf8("slt_downpath_bttn_l"))
        self.downloadLabel_l = QtGui.QLabel(self.tab)
        self.downloadLabel_l.setGeometry(QtCore.QRect(320, 342, 54, 16))
        self.downloadLabel_l.setObjectName(_fromUtf8("downloadLabel_l"))
        self.downloadBar_l = QtGui.QProgressBar(self.tab)
        self.downloadBar_l.setGeometry(QtCore.QRect(110, 340, 201, 23))
        self.downloadBar_l.setProperty("value", 24)
        self.downloadBar_l.setObjectName(_fromUtf8("downloadBar_l"))
        self.search_bttn_l = QtGui.QPushButton(self.tab)
        self.search_bttn_l.setGeometry(QtCore.QRect(20, 300, 75, 23))
        self.search_bttn_l.setObjectName(_fromUtf8("search_bttn_l"))
        self.download_bttn_l = QtGui.QPushButton(self.tab)
        self.download_bttn_l.setGeometry(QtCore.QRect(20, 340, 75, 23))
        self.download_bttn_l.setObjectName(_fromUtf8("download_bttn_l"))
        self.groupBox_6 = QtGui.QGroupBox(self.tab)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 10, 391, 81))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.label_13 = QtGui.QLabel(self.groupBox_6)
        self.label_13.setGeometry(QtCore.QRect(16, 34, 54, 12))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.groupBox_6)
        self.label_14.setGeometry(QtCore.QRect(178, 34, 54, 12))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.year_1 = QtGui.QComboBox(self.groupBox_6)
        self.year_1.setGeometry(QtCore.QRect(40, 30, 101, 22))
        self.year_1.setObjectName(_fromUtf8("year_1"))
        self.month_l = QtGui.QComboBox(self.groupBox_6)
        self.month_l.setGeometry(QtCore.QRect(200, 30, 101, 22))
        self.month_l.setObjectName(_fromUtf8("month_l"))
        self.tabwidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.search_bttn_s = QtGui.QPushButton(self.tab_2)
        self.search_bttn_s.setGeometry(QtCore.QRect(20, 300, 75, 23))
        self.search_bttn_s.setObjectName(_fromUtf8("search_bttn_s"))
        self.download_bttn_s = QtGui.QPushButton(self.tab_2)
        self.download_bttn_s.setGeometry(QtCore.QRect(20, 340, 75, 23))
        self.download_bttn_s.setObjectName(_fromUtf8("download_bttn_s"))
        self.searchBar_s = QtGui.QProgressBar(self.tab_2)
        self.searchBar_s.setGeometry(QtCore.QRect(110, 300, 201, 23))
        self.searchBar_s.setProperty("value", 24)
        self.searchBar_s.setObjectName(_fromUtf8("searchBar_s"))
        self.downloadBar_s = QtGui.QProgressBar(self.tab_2)
        self.downloadBar_s.setGeometry(QtCore.QRect(110, 340, 201, 23))
        self.downloadBar_s.setProperty("value", 24)
        self.downloadBar_s.setObjectName(_fromUtf8("downloadBar_s"))
        self.outLabel_s = QtGui.QLabel(self.tab_2)
        self.outLabel_s.setGeometry(QtCore.QRect(320, 300, 71, 21))
        self.outLabel_s.setObjectName(_fromUtf8("outLabel_s"))
        self.downloadLabel_s = QtGui.QLabel(self.tab_2)
        self.downloadLabel_s.setGeometry(QtCore.QRect(320, 342, 54, 16))
        self.downloadLabel_s.setObjectName(_fromUtf8("downloadLabel_s"))
        self.groupBox_7 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 10, 391, 81))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.label_15 = QtGui.QLabel(self.groupBox_7)
        self.label_15.setGeometry(QtCore.QRect(16, 34, 54, 12))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.groupBox_7)
        self.label_16.setGeometry(QtCore.QRect(178, 34, 54, 12))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.year_s = QtGui.QComboBox(self.groupBox_7)
        self.year_s.setGeometry(QtCore.QRect(40, 30, 101, 22))
        self.year_s.setObjectName(_fromUtf8("year_s"))
        self.month_s = QtGui.QComboBox(self.groupBox_7)
        self.month_s.setGeometry(QtCore.QRect(200, 30, 101, 22))
        self.month_s.setObjectName(_fromUtf8("month_s"))
        self.groupBox_8 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 190, 391, 101))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.label_17 = QtGui.QLabel(self.groupBox_8)
        self.label_17.setGeometry(QtCore.QRect(10, 30, 54, 12))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(self.groupBox_8)
        self.label_18.setGeometry(QtCore.QRect(10, 63, 54, 12))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.savecsv_s = QtGui.QLineEdit(self.groupBox_8)
        self.savecsv_s.setGeometry(QtCore.QRect(60, 28, 241, 20))
        self.savecsv_s.setObjectName(_fromUtf8("savecsv_s"))
        self.savedownload_s = QtGui.QLineEdit(self.groupBox_8)
        self.savedownload_s.setGeometry(QtCore.QRect(60, 60, 241, 20))
        self.savedownload_s.setObjectName(_fromUtf8("savedownload_s"))
        self.slt_csv_bttn_s = QtGui.QPushButton(self.groupBox_8)
        self.slt_csv_bttn_s.setGeometry(QtCore.QRect(310, 27, 75, 23))
        self.slt_csv_bttn_s.setObjectName(_fromUtf8("slt_csv_bttn_s"))
        self.slt_downpath_bttn_s = QtGui.QPushButton(self.groupBox_8)
        self.slt_downpath_bttn_s.setGeometry(QtCore.QRect(310, 60, 75, 23))
        self.slt_downpath_bttn_s.setObjectName(_fromUtf8("slt_downpath_bttn_s"))
        self.groupBox_9 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 100, 391, 80))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.sate_s = QtGui.QComboBox(self.groupBox_9)
        self.sate_s.setGeometry(QtCore.QRect(40, 30, 101, 22))
        self.sate_s.setObjectName(_fromUtf8("sate_s"))
        self.label_19 = QtGui.QLabel(self.groupBox_9)
        self.label_19.setGeometry(QtCore.QRect(10, 35, 54, 12))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_20 = QtGui.QLabel(self.groupBox_9)
        self.label_20.setGeometry(QtCore.QRect(170, 34, 54, 12))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.cloud_s = QtGui.QComboBox(self.groupBox_9)
        self.cloud_s.setGeometry(QtCore.QRect(220, 30, 101, 22))
        self.cloud_s.setObjectName(_fromUtf8("cloud_s"))
        self.label_21 = QtGui.QLabel(self.groupBox_9)
        self.label_21.setGeometry(QtCore.QRect(200, 30, 16, 21))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.tabwidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.download_bttn_sar_3 = QtGui.QPushButton(self.tab_3)
        self.download_bttn_sar_3.setGeometry(QtCore.QRect(20, 338, 75, 23))
        self.download_bttn_sar_3.setObjectName(_fromUtf8("download_bttn_sar_3"))
        self.outLabel_sar_3 = QtGui.QLabel(self.tab_3)
        self.outLabel_sar_3.setGeometry(QtCore.QRect(320, 298, 71, 21))
        self.outLabel_sar_3.setObjectName(_fromUtf8("outLabel_sar_3"))
        self.groupBox_16 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_16.setGeometry(QtCore.QRect(10, 20, 391, 80))
        self.groupBox_16.setObjectName(_fromUtf8("groupBox_16"))
        self.sate_sar_3 = QtGui.QComboBox(self.groupBox_16)
        self.sate_sar_3.setGeometry(QtCore.QRect(70, 30, 101, 22))
        self.sate_sar_3.setObjectName(_fromUtf8("sate_sar_3"))
        self.label_36 = QtGui.QLabel(self.groupBox_16)
        self.label_36.setGeometry(QtCore.QRect(10, 35, 54, 12))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.sate_sar_3.raise_()
        self.label_36.raise_()
        self.searchBar_sar_3 = QtGui.QProgressBar(self.tab_3)
        self.searchBar_sar_3.setGeometry(QtCore.QRect(110, 298, 201, 23))
        self.searchBar_sar_3.setProperty("value", 24)
        self.searchBar_sar_3.setObjectName(_fromUtf8("searchBar_sar_3"))
        self.search_bttn_sar_3 = QtGui.QPushButton(self.tab_3)
        self.search_bttn_sar_3.setGeometry(QtCore.QRect(20, 298, 75, 23))
        self.search_bttn_sar_3.setObjectName(_fromUtf8("search_bttn_sar_3"))
        self.groupBox_17 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_17.setGeometry(QtCore.QRect(10, 188, 391, 101))
        self.groupBox_17.setObjectName(_fromUtf8("groupBox_17"))
        self.label_39 = QtGui.QLabel(self.groupBox_17)
        self.label_39.setGeometry(QtCore.QRect(10, 30, 54, 12))
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.label_40 = QtGui.QLabel(self.groupBox_17)
        self.label_40.setGeometry(QtCore.QRect(10, 63, 54, 12))
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.savecsv_sar_3 = QtGui.QLineEdit(self.groupBox_17)
        self.savecsv_sar_3.setGeometry(QtCore.QRect(60, 28, 241, 20))
        self.savecsv_sar_3.setObjectName(_fromUtf8("savecsv_sar_3"))
        self.savedownload_sar_3 = QtGui.QLineEdit(self.groupBox_17)
        self.savedownload_sar_3.setGeometry(QtCore.QRect(60, 60, 241, 20))
        self.savedownload_sar_3.setObjectName(_fromUtf8("savedownload_sar_3"))
        self.slt_csv_bttn_sar_3 = QtGui.QPushButton(self.groupBox_17)
        self.slt_csv_bttn_sar_3.setGeometry(QtCore.QRect(310, 27, 75, 23))
        self.slt_csv_bttn_sar_3.setObjectName(_fromUtf8("slt_csv_bttn_sar_3"))
        self.slt_downpath_bttn_sar_3 = QtGui.QPushButton(self.groupBox_17)
        self.slt_downpath_bttn_sar_3.setGeometry(QtCore.QRect(310, 60, 75, 23))
        self.slt_downpath_bttn_sar_3.setObjectName(_fromUtf8("slt_downpath_bttn_sar_3"))
        self.downloadBar_sar_3 = QtGui.QProgressBar(self.tab_3)
        self.downloadBar_sar_3.setGeometry(QtCore.QRect(110, 338, 201, 23))
        self.downloadBar_sar_3.setProperty("value", 24)
        self.downloadBar_sar_3.setObjectName(_fromUtf8("downloadBar_sar_3"))
        self.groupBox_18 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_18.setGeometry(QtCore.QRect(10, 100, 391, 81))
        self.groupBox_18.setObjectName(_fromUtf8("groupBox_18"))
        self.label_41 = QtGui.QLabel(self.groupBox_18)
        self.label_41.setGeometry(QtCore.QRect(16, 34, 54, 12))
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.year_sar_3 = QtGui.QComboBox(self.groupBox_18)
        self.year_sar_3.setGeometry(QtCore.QRect(70, 30, 101, 22))
        self.year_sar_3.setObjectName(_fromUtf8("year_sar_3"))
        self.downloadLabel_sar3 = QtGui.QLabel(self.tab_3)
        self.downloadLabel_sar3.setGeometry(QtCore.QRect(320, 340, 54, 16))
        self.downloadLabel_sar3.setObjectName(_fromUtf8("downloadLabel_sar3"))
        self.tabwidget.addTab(self.tab_3, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabwidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.outLabel_l.setText(_translate("MainWindow", "TextLabel", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "数据类型", None))
        self.label_8.setText(_translate("MainWindow", "卫星", None))
        self.label_9.setText(_translate("MainWindow", "云量", None))
        self.label_10.setText(_translate("MainWindow", "<=", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "下载输出", None))
        self.label_11.setText(_translate("MainWindow", "csv保存", None))
        self.label_12.setText(_translate("MainWindow", "下载位置", None))
        self.slt_csv_bttn_l.setText(_translate("MainWindow", "选择", None))
        self.slt_downpath_bttn_l.setText(_translate("MainWindow", "选择", None))
        self.downloadLabel_l.setText(_translate("MainWindow", "TextLabel", None))
        self.search_bttn_l.setText(_translate("MainWindow", "开始检索", None))
        self.download_bttn_l.setText(_translate("MainWindow", "开始下载", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "时间", None))
        self.label_13.setText(_translate("MainWindow", "年", None))
        self.label_14.setText(_translate("MainWindow", "月", None))
        self.tabwidget.setTabText(self.tabwidget.indexOf(self.tab), _translate("MainWindow", "Landsat", None))
        self.search_bttn_s.setText(_translate("MainWindow", "开始检索", None))
        self.download_bttn_s.setText(_translate("MainWindow", "开始下载", None))
        self.outLabel_s.setText(_translate("MainWindow", "TextLabel", None))
        self.downloadLabel_s.setText(_translate("MainWindow", "TextLabel", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "时间", None))
        self.label_15.setText(_translate("MainWindow", "年", None))
        self.label_16.setText(_translate("MainWindow", "月", None))
        self.groupBox_8.setTitle(_translate("MainWindow", "下载输出", None))
        self.label_17.setText(_translate("MainWindow", "csv保存", None))
        self.label_18.setText(_translate("MainWindow", "下载位置", None))
        self.slt_csv_bttn_s.setText(_translate("MainWindow", "选择", None))
        self.slt_downpath_bttn_s.setText(_translate("MainWindow", "选择", None))
        self.groupBox_9.setTitle(_translate("MainWindow", "数据类型", None))
        self.label_19.setText(_translate("MainWindow", "卫星", None))
        self.label_20.setText(_translate("MainWindow", "云量", None))
        self.label_21.setText(_translate("MainWindow", "<=", None))
        self.tabwidget.setTabText(self.tabwidget.indexOf(self.tab_2), _translate("MainWindow", "Sentinel", None))
        self.download_bttn_sar_3.setText(_translate("MainWindow", "开始下载", None))
        self.outLabel_sar_3.setText(_translate("MainWindow", "TextLabel", None))
        self.groupBox_16.setTitle(_translate("MainWindow", "数据类型", None))
        self.label_36.setText(_translate("MainWindow", "卫星", None))
        self.search_bttn_sar_3.setText(_translate("MainWindow", "开始检索", None))
        self.groupBox_17.setTitle(_translate("MainWindow", "下载输出", None))
        self.label_39.setText(_translate("MainWindow", "csv保存", None))
        self.label_40.setText(_translate("MainWindow", "下载位置", None))
        self.slt_csv_bttn_sar_3.setText(_translate("MainWindow", "选择", None))
        self.slt_downpath_bttn_sar_3.setText(_translate("MainWindow", "选择", None))
        self.groupBox_18.setTitle(_translate("MainWindow", "时间", None))
        self.label_41.setText(_translate("MainWindow", "年-月", None))
        self.downloadLabel_sar3.setText(_translate("MainWindow", "TextLabel", None))
        self.tabwidget.setTabText(self.tabwidget.indexOf(self.tab_3), _translate("MainWindow", "SAR", None))

